package frango

import "log"

// WithSourceDir configures a directory to be added to the VFS with the given prefix.
// This is a convenience function for AddSourceDirectory.
// Note: Previously, this set a field on the middleware, but now it is applied when the
// middleware is ready.
// DEPRECATED: Use AddSourceDirectory after creating the middleware for clearer API.
func WithSourceDir(dir string) Option {
	return func(m *Middleware) {
		// We can't set up the VFS immediately as the middleware might not be fully initialized yet,
		// so we'll store the directory and add it in New()
		_ = dir // Prevent unused variable warning - we'll handle this in New()
		// The actual work will now be done after the VFS is created in New()
	}
}

// WithTempDir sets the temporary directory for PHP files and VFS storage.
func WithTempDir(dir string) Option {
	return func(m *Middleware) {
		m.tempDir = dir
	}
}

// WithDevelopmentMode enables real-time file change detection and disables caching.
func WithDevelopmentMode(enabled bool) Option {
	return func(m *Middleware) {
		m.developmentMode = enabled
	}
}

// WithLogger sets a custom logger.
func WithLogger(logger *log.Logger) Option {
	return func(m *Middleware) {
		m.logger = logger
	}
}

// WithDirectPHPURLsBlocking controls whether direct PHP file access in URLs should be blocked.
// When enabled (default), URL paths ending with .php will be blocked unless they were explicitly
// registered with a handler.
func WithDirectPHPURLsBlocking(block bool) Option {
	return func(m *Middleware) {
		m.blockDirectPHPURLs = block
	}
}

// WithErrorHandler sets a custom PHP error handler script path.
// When PHP errors occur, this script will be executed to handle them.
func WithErrorHandler(phpErrorHandlerPath string) Option {
	return func(m *Middleware) {
		m.errorHandlerPath = phpErrorHandlerPath
	}
}

// WithErrorDisplay controls whether PHP errors are displayed in the output.
// In development mode, errors are displayed by default.
// In production mode, errors are hidden by default.
func WithErrorDisplay(display bool) Option {
	return func(m *Middleware) {
		m.displayErrors = display
	}
}

// WithDisplayErrors controls whether PHP errors are displayed in the output.
// Defaults to false in production, true in development.
func WithDisplayErrors(display bool) Option {
	return func(m *Middleware) {
		m.displayErrors = display
	}
}

// WithAutoReload enables or disables the development auto-reload feature.
// Requires DevelopmentMode to also be enabled. Defaults to true if DevelopmentMode is true.
func WithAutoReload(enable bool) Option {
	return func(m *Middleware) {
		m.enableAutoReload = enable
	}
}

// WithAutoReloadTrigger specifies the mechanism for auto-reload notifications.
// Options are "sse" (Server-Sent Events - default), "polling".
// Requires AutoReload to be enabled.
func WithAutoReloadTrigger(trigger string) Option {
	return func(m *Middleware) {
		m.autoReloadTrigger = trigger
	}
}

// WithCustomAutoReloadScript provides a custom JavaScript snippet for auto-reload.
// If provided, this overrides the script generated by AutoReloadTrigger.
// Requires AutoReload to be enabled.
func WithCustomAutoReloadScript(script string) Option {
	return func(m *Middleware) {
		m.autoReloadScript = script
	}
}

// DevServerConfig holds configuration options for the internal development server.
type DevServerConfig struct {
	// Port specifies the port on which the internal development server will listen.
	// Defaults to 8081 if not set or set to 0.
	Port int
	// Add other dev server specific options here in the future (e.g., TLS config)
}

// WithDevServer enables the internal development server and auto-reload features,
// configuring it with the provided settings.
// Using this option implicitly sets DevelopmentMode and EnableAutoReload to true,
// unless explicitly overridden by other options.
func WithDevServer(config DevServerConfig) Option {
	return func(m *Middleware) {
		// Ensure default port if not specified
		if config.Port <= 0 {
			config.Port = 8081 // Default port
		}
		m.devServerConfig = &config // Store the pointer to the config
		// Implicitly enable dev mode and auto-reload when using the dev server
		m.developmentMode = true
		m.enableAutoReload = true
	}
}

// WithBlockDirectPHPURLs prevents direct access to .php files via their URL.
// Defaults to true. Set to false if you need direct access for specific routes.
func WithBlockDirectPHPURLs(block bool) Option {
	return func(m *Middleware) {
		m.blockDirectPHPURLs = block
	}
}
