<?php
/**
 * Frango v2 Demo - Rendering with Data From Go
 * 
 * Demonstrates how to render a PHP template with data provided by a Go handler
 * using middleware.Render().
 * 
 * In Go: middleware.Render("/integration/render_from_go.php", renderDataFunc)
 * In PHP: Access data via $GLOBALS['_TEMPLATE']
 */

// Data provided by Go is available in $GLOBALS['_TEMPLATE']
$data = $GLOBALS['_TEMPLATE'] ?? [];

// Extract data for convenience
$message = $data['message'] ?? 'No message provided';
$timestamp = $data['timestamp'] ?? date('c');
$requestIP = $data['requestIP'] ?? $_SERVER['REMOTE_ADDR'];

// Add some PHP-generated data to demonstrate mixing
$phpData = [
    'time' => date('H:i:s'),
    'memory_usage' => formatBytes(memory_get_usage()),
    'php_version' => PHP_VERSION,
    'timezone' => date_default_timezone_get()
];

// Helper function to format bytes
function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    
    $bytes /= pow(1024, $pow);
    
    return round($bytes, $precision) . ' ' . $units[$pow];
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frango v2 - Go → PHP Rendering</title>
    <link rel="stylesheet" href="/assets/style.css">
</head>
<body>
    <div class="container">
        <h1>Go → PHP Data Integration</h1>
        <p>This page demonstrates how Go can pass data to PHP templates when rendering.</p>

        <div class="card">
            <h2>Data Received from Go</h2>
            <div style="background-color: #f0fff4; border-left: 4px solid #68d391; padding: 15px; margin-bottom: 20px;">
                <strong style="font-size: 1.2em;"><?= htmlspecialchars($message) ?></strong>
                <div>Sent at: <?= htmlspecialchars($timestamp) ?></div>
                <div>Your IP: <?= htmlspecialchars($requestIP) ?></div>
            </div>
            
            <h3>Raw Template Data ($GLOBALS['_TEMPLATE'])</h3>
            <pre><?php var_export($data); ?></pre>
        </div>
        
        <div class="card">
            <h2>Additional PHP Data</h2>
            <div style="background-color: #ebf8ff; border-left: 4px solid #4299e1; padding: 15px; margin-bottom: 20px;">
                <p>Data generated by PHP at rendering time:</p>
                <ul>
                    <li><strong>Local Time:</strong> <?= htmlspecialchars($phpData['time']) ?></li>
                    <li><strong>Memory Usage:</strong> <?= htmlspecialchars($phpData['memory_usage']) ?></li>
                    <li><strong>PHP Version:</strong> <?= htmlspecialchars($phpData['php_version']) ?></li>
                    <li><strong>Timezone:</strong> <?= htmlspecialchars($phpData['timezone']) ?></li>
                </ul>
            </div>
        </div>
        
        <div class="card">
            <h2>How It Works</h2>
            <p>This demonstration uses Frango's render functionality to pass data from Go handlers to PHP templates:</p>
            
            <h3>1. Go Handler Code</h3>
            <pre style="background: #2c3e50; color: #fff; padding: 15px; border-radius: 4px;">
// Define a Go handler function that returns data for PHP
func renderDataFunc(w http.ResponseWriter, r *http.Request) map[string]interface{} {
    return map[string]interface{}{
        "message":   "Hello from Go!",
        "timestamp": time.Now().Format(time.RFC3339),
        "requestIP": r.RemoteAddr,
    }
}

// In main.go, register the route
mux.Handle("/render", middleware.Render("/integration/render_from_go.php", renderDataFunc))
            </pre>
            
            <h3>2. PHP Template Code</h3>
            <pre style="background: #2c3e50; color: #fff; padding: 15px; border-radius: 4px;">
// Access data from Go
$data = $GLOBALS['_TEMPLATE'] ?? [];

// Extract specific values
$message = $data['message'] ?? 'Default Message';
$timestamp = $data['timestamp'] ?? 'Unknown';

// Use the data in your template
echo "&lt;h2&gt;$message&lt;/h2&gt;";
echo "&lt;p&gt;Received at: $timestamp&lt;/p&gt;";
            </pre>
        </div>
        
        <div class="card">
            <h2>Use Cases</h2>
            <p>This integration pattern is useful for:</p>
            <ul>
                <li><strong>Admin Dashboards</strong> - Pass live system metrics from Go to PHP templates</li>
                <li><strong>Data Processing</strong> - Perform complex data operations in Go before rendering in PHP</li>
                <li><strong>Authentication</strong> - Verify credentials in Go and pass user data to PHP</li>
                <li><strong>API Integration</strong> - Fetch external API data in Go and pass to PHP for rendering</li>
            </ul>
        </div>
        
        <div class="card">
            <h2>Navigation</h2>
            <p><a href="/api/time" target="_blank">Try the Go JSON API</a></p>
            <p><a href="/">Back to Dashboard</a></p>
        </div>
    </div>
    
    <!-- Include the debug panel -->
    <?php include dirname(dirname(__FILE__)) . '/debug_panel.php'; ?>
</body>
</html> 